### ISSUE TITLE
Can't build under android

### ISSUE THREAD

**Issue by ivan133** [francisbrito/react-native-classroom-photos-app#1]
Hi!
I've cloned your project.
Run npm install 
and then react-native run-android
and got this:

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-camera:debugCompileClasspath'.
> Could not find common.jar (android.arch.core:common:1.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar

**Comment by ivan133** [comment]
Ok I found a solution https://github.com/facebook/react-native/issues/19485

**Comment by francisbrito** [comment]
Believe or not, I ran into the same issue on another project yesterday. Thanks for posting the solution @ivan133!
